Remove undefined variable `entryOverwrites` (#56)
When running the following command:

```
npx migrations content --source-environment-id master--dest-environment-id non-master --verbose --diff
```

And going through the process to resolve conflicts, the following error appears and aborts the whole process:

```
Error: entryOverwrites is not defined
```

This PR solves this problem by removing the reference to this undefined variable.